# -*- coding: utf-8 -*-
"""Copy of main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k9Gq9rE9bR2iWayl4o2s4dNc5DqnFOZE
"""

# !pip install pandas-datareader
# !pip install --upgrade pandas-datareader
import pandas as pd
import pandas_datareader.data as web
import numpy as np
import datetime
from matplotlib import pyplot as plt
plt.rcParams["figure.figsize"] = (20,10)

start = datetime.datetime(2020,6,14)
end   = datetime.datetime(2022,6,14)

aemulus = web.DataReader("0181.KL","yahoo",start,end)['Close']
jftech = web.DataReader("0146.KL","yahoo",start,end)['Close']
penta = web.DataReader("7160.KL","yahoo",start,end)['Close']
dAndO = web.DataReader("7204.KL","yahoo",start,end)['Close']
dufu = web.DataReader("7233.KL","yahoo",start,end)['Close']
inari = web.DataReader("0166.KL","yahoo",start,end)['Close']
jhm = web.DataReader("0127.KL","yahoo",start,end)['Close']
mpi = web.DataReader("3867.KL","yahoo",start,end)['Close']
mi = web.DataReader("5286.KL","yahoo",start,end)['Close']

data = pd.concat([aemulus,jftech, penta, dAndO, dufu, inari, jhm, mpi, mi], axis=1)
normalized = data.div(data.iloc[0]).mul(100)
# Rename 
normalized.columns = ["aemulus", "jftech", "penta","dAndO", "dufu", "inari","jhm", "mpi", "mi"]
normalized.plot()
plt.show()
